// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockLogger.Data;

#nullable disable

namespace StockLogger.Migrations
{
    [DbContext(typeof(StockLoggerDbContext))]
    [Migration("20241226111947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockLogger.Models.Candel.Candel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Candel");
                });

            modelBuilder.Entity("StockLogger.Models.Candel.Candel10min", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Candel10min");
                });

            modelBuilder.Entity("StockLogger.Models.Candel.Candel15min", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Candel15min");
                });

            modelBuilder.Entity("StockLogger.Models.Candel.Candel5min", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Candel5min");
                });

            modelBuilder.Entity("StockLogger.Models.Candel.StockPricePerSec", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("StockDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StockPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("StockPricePerSec");
                });

            modelBuilder.Entity("StockLogger.Models.Candel.StockTickerExchange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StockTickerExchanges");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Bullish_Engulfing.BullishEngulfingCandels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BullishEngulfingDbId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BullishEngulfingDbId");

                    b.ToTable("BullishEngulfingCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Bullish_Engulfing.BullishEngulfingDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DetectionRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBullishEngulfingDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BullishEngulfingDb");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Bullish_Harami.BullishHaramiCandels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BullishHaramiDbId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BullishHaramiDbId");

                    b.ToTable("BullishHaramiCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Bullish_Harami.BullishHaramiDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DetectionRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBullishHaramiDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BullishHaramiDb");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Dragonfly_Doji.DragonflyDojiCandels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DragonflyDojiDbId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DragonflyDojiDbId");

                    b.ToTable("DragonflyDojiCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Dragonfly_Doji.DragonflyDojiDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DetectionRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDragonflyDojiDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DragonflyDojiDb");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Hammer.HammerCandels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("HammerDbId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HammerDbId");

                    b.ToTable("HammerCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Hammer.HammerDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DetectionRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHammerDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("HammerDb");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Inverted_Hammer.InvertedHammerCandels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("InvertedHammerDbId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InvertedHammerDbId");

                    b.ToTable("InvertedHammerCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Inverted_Hammer.InvertedHammerDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DetectionRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInvertedHammerDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("InvertedHammerDb");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Morning_Star.MorningStarCandels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("MorningStarDbId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MorningStarDbId");

                    b.ToTable("MorningStarCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Morning_Star.MorningStarDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DetectionRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMorningStarDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MorningStarDb");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Piercing_Line.PiercingLineCandels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PiercingLineDbId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PiercingLineDbId");

                    b.ToTable("PiercingLineCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Piercing_Line.PiercingLineDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DetectionRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPiercingLineDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PiercingLineDb");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Rising_Three_Methods.RisingThreeMethodsCandels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("RisingThreeMethodsDbId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RisingThreeMethodsDbId");

                    b.ToTable("RisingThreeMethodsCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Rising_Three_Methods.RisingThreeMethodsDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DetectionRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRisingThreeMethodsDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RisingThreeMethodsDb");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.ThreeWhiteSoilderCandels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("ThreeWhiteSoilderDbId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ThreeWhiteSoilderDbId");

                    b.ToTable("ThreeWhiteSoilderCandelss");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.ThreeWhiteSoilderDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DetectionRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsThreeWhiteSoilderDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ThreeWhiteSoilderDbs");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Tweezer_Bottom.TweezerBottomCandels", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsBearish")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBullish")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceChangePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TweezerBottomDbId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TweezerBottomDbId");

                    b.ToTable("TweezerBottomCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Tweezer_Bottom.TweezerBottomDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DetectionRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("DetectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTweezerBottomDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TickerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TweezerBottomDb");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Bullish_Engulfing.BullishEngulfingCandels", b =>
                {
                    b.HasOne("StockLogger.Models.Stratergic_Models.Bullish_Engulfing.BullishEngulfingDb", null)
                        .WithMany("BullishEngulfingCandels")
                        .HasForeignKey("BullishEngulfingDbId");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Bullish_Harami.BullishHaramiCandels", b =>
                {
                    b.HasOne("StockLogger.Models.Stratergic_Models.Bullish_Harami.BullishHaramiDb", null)
                        .WithMany("BullishHaramiCandels")
                        .HasForeignKey("BullishHaramiDbId");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Dragonfly_Doji.DragonflyDojiCandels", b =>
                {
                    b.HasOne("StockLogger.Models.Stratergic_Models.Dragonfly_Doji.DragonflyDojiDb", null)
                        .WithMany("DragonflyDojiCandels")
                        .HasForeignKey("DragonflyDojiDbId");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Hammer.HammerCandels", b =>
                {
                    b.HasOne("StockLogger.Models.Stratergic_Models.Hammer.HammerDb", null)
                        .WithMany("HammerCandels")
                        .HasForeignKey("HammerDbId");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Inverted_Hammer.InvertedHammerCandels", b =>
                {
                    b.HasOne("StockLogger.Models.Stratergic_Models.Inverted_Hammer.InvertedHammerDb", null)
                        .WithMany("InvertedHammerCandels")
                        .HasForeignKey("InvertedHammerDbId");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Morning_Star.MorningStarCandels", b =>
                {
                    b.HasOne("StockLogger.Models.Stratergic_Models.Morning_Star.MorningStarDb", null)
                        .WithMany("MorningStarCandels")
                        .HasForeignKey("MorningStarDbId");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Piercing_Line.PiercingLineCandels", b =>
                {
                    b.HasOne("StockLogger.Models.Stratergic_Models.Piercing_Line.PiercingLineDb", null)
                        .WithMany("PiercingLineCandels")
                        .HasForeignKey("PiercingLineDbId");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Rising_Three_Methods.RisingThreeMethodsCandels", b =>
                {
                    b.HasOne("StockLogger.Models.Stratergic_Models.Rising_Three_Methods.RisingThreeMethodsDb", null)
                        .WithMany("RisingThreeMethodsCandels")
                        .HasForeignKey("RisingThreeMethodsDbId");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.ThreeWhiteSoilderCandels", b =>
                {
                    b.HasOne("StockLogger.Models.Stratergic_Models.ThreeWhiteSoilderDb", null)
                        .WithMany("ThreeWhiteSoilderCandels")
                        .HasForeignKey("ThreeWhiteSoilderDbId");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Tweezer_Bottom.TweezerBottomCandels", b =>
                {
                    b.HasOne("StockLogger.Models.Stratergic_Models.Tweezer_Bottom.TweezerBottomDb", null)
                        .WithMany("TweezerBottomCandels")
                        .HasForeignKey("TweezerBottomDbId");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Bullish_Engulfing.BullishEngulfingDb", b =>
                {
                    b.Navigation("BullishEngulfingCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Bullish_Harami.BullishHaramiDb", b =>
                {
                    b.Navigation("BullishHaramiCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Dragonfly_Doji.DragonflyDojiDb", b =>
                {
                    b.Navigation("DragonflyDojiCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Hammer.HammerDb", b =>
                {
                    b.Navigation("HammerCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Inverted_Hammer.InvertedHammerDb", b =>
                {
                    b.Navigation("InvertedHammerCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Morning_Star.MorningStarDb", b =>
                {
                    b.Navigation("MorningStarCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Piercing_Line.PiercingLineDb", b =>
                {
                    b.Navigation("PiercingLineCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Rising_Three_Methods.RisingThreeMethodsDb", b =>
                {
                    b.Navigation("RisingThreeMethodsCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.ThreeWhiteSoilderDb", b =>
                {
                    b.Navigation("ThreeWhiteSoilderCandels");
                });

            modelBuilder.Entity("StockLogger.Models.Stratergic_Models.Tweezer_Bottom.TweezerBottomDb", b =>
                {
                    b.Navigation("TweezerBottomCandels");
                });
#pragma warning restore 612, 618
        }
    }
}
