using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Identity.Client.Platforms.Features.DesktopOs.Kerberos;
using Microsoft.VisualBasic;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
using System.ComponentModel;
using System.Diagnostics;
using System.Security.Cryptography;
using System.Web.Helpers;
using Microsoft.AspNetCore.Components;
using Microsoft.CodeAnalysis;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using static System.Net.Mime.MediaTypeNames;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Reflection;
using System.Runtime.Intrinsics.X86;
using System.Web.Razor.Parser.SyntaxTree;
using System;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.SignalR;
using Polly.Caching;
using static System.Net.WebRequestMethods;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Collections;
using System.Net.NetworkInformation;
using System.Numerics;
using System.Runtime.ConstrainedExecution;
using System.Runtime.InteropServices.JavaScript;
using System.Runtime.InteropServices;
using System.Security.Cryptography.Xml;

namespace StockLogger.Models.Candel
{
    public class StockList2
    {
    public static List<Stock> GetStocks()
    {
      return new List<Stock>
            {
                new Stock { Ticker = "360ONE-EQ", Exchange = "NSE", Name = "360ONE-EQ", Id = 1, SymbolToken = "13061" },
                new Stock { Ticker = "3MINDIA-EQ", Exchange = "NSE", Name = "3MINDIA-EQ", Id = 2, SymbolToken = "474" },
                new Stock { Ticker = "ABB-EQ", Exchange = "NSE", Name = "ABB-EQ", Id = 3, SymbolToken = "13" },
                new Stock { Ticker = "ACC-EQ", Exchange = "NSE", Name = "ACC-EQ", Id = 4, SymbolToken = "22" },
                new Stock { Ticker = "AIAENG-EQ", Exchange = "NSE", Name = "AIAENG-EQ", Id = 5, SymbolToken = "13086" },
                new Stock { Ticker = "APLAPOLLO-EQ", Exchange = "NSE", Name = "APLAPOLLO-EQ", Id = 6, SymbolToken = "25780" },
                new Stock { Ticker = "AUBANK-EQ", Exchange = "NSE", Name = "AUBANK-EQ", Id = 7, SymbolToken = "21238" },
                new Stock { Ticker = "AADHARHFC-EQ", Exchange = "NSE", Name = "AADHARHFC-EQ", Id = 8, SymbolToken = "23729" },
                new Stock { Ticker = "AARTIIND-EQ", Exchange = "NSE", Name = "AARTIIND-EQ", Id = 9, SymbolToken = "7" },
                new Stock { Ticker = "AAVAS-EQ", Exchange = "NSE", Name = "AAVAS-EQ", Id = 10, SymbolToken = "5385" },
                new Stock { Ticker = "ABBOTINDIA-EQ", Exchange = "NSE", Name = "ABBOTINDIA-EQ", Id = 11, SymbolToken = "17903" },
                new Stock { Ticker = "ACE-EQ", Exchange = "NSE", Name = "ACE-EQ", Id = 12, SymbolToken = "13587" },

                new Stock { Ticker = "ADANIENSOL-EQ", Exchange = "NSE", Name = "ADANIENSOL-EQ", Id = 13, SymbolToken = "10217" },
                new Stock { Ticker = "ADANIENT-EQ", Exchange = "NSE", Name = "ADANIENT-EQ", Id = 14, SymbolToken = "25" },
                new Stock { Ticker = "ADANIGREEN-EQ", Exchange = "NSE", Name = "ADANIGREEN-EQ", Id = 15, SymbolToken = "3563" },
                new Stock { Ticker = "ADANIPORTS-EQ", Exchange = "NSE", Name = "ADANIPORTS-EQ", Id = 16, SymbolToken = "15083" },
                new Stock { Ticker = "ADANIPOWER-EQ", Exchange = "NSE", Name = "ADANIPOWER-EQ", Id = 17, SymbolToken = "17388" },

                new Stock { Ticker = "ATGL-EQ", Exchange = "NSE", Name = "ATGL-EQ", Id = 18, SymbolToken = "6066" },
                new Stock { Ticker = "AWL-EQ", Exchange = "NSE", Name = "AWL-EQ", Id = 19, SymbolToken = "8110" },
                new Stock { Ticker = "ABCAPITAL-EQ", Exchange = "NSE", Name = "ABCAPITAL-EQ", Id = 20, SymbolToken = "21614" },
                new Stock { Ticker = "ABFRL-EQ", Exchange = "NSE", Name = "ABFRL-EQ", Id = 21, SymbolToken = "30108" },
                new Stock { Ticker = "ABREL-EQ", Exchange = "NSE", Name = "ABREL-EQ", Id = 22, SymbolToken = "625" },
                new Stock { Ticker = "ABSLAMC-EQ", Exchange = "NSE", Name = "ABSLAMC-EQ", Id = 23, SymbolToken = "6018" },
                new Stock { Ticker = "AEGISLOG-EQ", Exchange = "NSE", Name = "AEGISLOG-EQ", Id = 24, SymbolToken = "40" },
                new Stock { Ticker = "AFFLE-EQ", Exchange = "NSE", Name = "AFFLE-EQ", Id = 25, SymbolToken = "11343" },
                new Stock { Ticker = "AJANTPHARM-EQ", Exchange = "NSE", Name = "AJANTPHARM-EQ", Id = 26, SymbolToken = "8124" },
                new Stock { Ticker = "AKUMS-EQ", Exchange = "NSE", Name = "AKUMS-EQ", Id = 27, SymbolToken = "24715" },
                new Stock { Ticker = "APLLTD-EQ", Exchange = "NSE", Name = "APLLTD-EQ", Id = 28, SymbolToken = "25328" },
                new Stock { Ticker = "ALKEM-EQ", Exchange = "NSE", Name = "ALKEM-EQ", Id = 29, SymbolToken = "11703" },
                new Stock { Ticker = "ALKYLAMINE-EQ", Exchange = "NSE", Name = "ALKYLAMINE-EQ", Id = 30, SymbolToken = "4487" },
                new Stock { Ticker = "ALOKINDS-EQ", Exchange = "NSE", Name = "ALOKINDS-EQ", Id = 31, SymbolToken = "17675" },
                new Stock { Ticker = "ARE%26M-EQ", Exchange = "NSE", Name = "ARE%26M-EQ", Id = 32, SymbolToken = "100" },
                new Stock { Ticker = "AMBER-EQ", Exchange = "NSE", Name = "AMBER-EQ", Id = 33, SymbolToken = "1185" },
                new Stock { Ticker = "AMBUJACEM-EQ", Exchange = "NSE", Name = "AMBUJACEM-EQ", Id = 34, SymbolToken = "1270" },
                new Stock { Ticker = "ANANDRATHI-EQ", Exchange = "NSE", Name = "ANANDRATHI-EQ", Id = 35, SymbolToken = "7145" },
                new Stock { Ticker = "ANANTRAJ-EQ", Exchange = "NSE", Name = "ANANTRAJ-EQ", Id = 36, SymbolToken = "13620" },
                new Stock { Ticker = "ANGELONE-EQ", Exchange = "NSE", Name = "ANGELONE-EQ", Id = 37, SymbolToken = "324" },
                new Stock { Ticker = "APARINDS-EQ", Exchange = "NSE", Name = "APARINDS-EQ", Id = 38, SymbolToken = "11491" },
                new Stock { Ticker = "APOLLOHOSP-EQ", Exchange = "NSE", Name = "APOLLOHOSP-EQ", Id = 39, SymbolToken = "157" },
                new Stock { Ticker = "APOLLOTYRE-EQ", Exchange = "NSE", Name = "APOLLOTYRE-EQ", Id = 40, SymbolToken = "163" },
                new Stock { Ticker = "APTUS-EQ", Exchange = "NSE", Name = "APTUS-EQ", Id = 41, SymbolToken = "5435" },
                new Stock { Ticker = "ACI-EQ", Exchange = "NSE", Name = "ACI-EQ", Id = 42, SymbolToken = "12024" },
                new Stock { Ticker = "ASAHIINDIA-EQ", Exchange = "NSE", Name = "ASAHIINDIA-EQ", Id = 43, SymbolToken = "5378" },
                new Stock { Ticker = "ASHOKLEY-EQ", Exchange = "NSE", Name = "ASHOKLEY-EQ", Id = 44, SymbolToken = "212" },
                new Stock { Ticker = "ASIANPAINT-EQ", Exchange = "NSE", Name = "ASIANPAINT-EQ", Id = 45, SymbolToken = "236" },
                new Stock { Ticker = "ASTERDM-EQ", Exchange = "NSE", Name = "ASTERDM-EQ", Id = 46, SymbolToken = "1508" },
                new Stock { Ticker = "ASTRAZEN-EQ", Exchange = "NSE", Name = "ASTRAZEN-EQ", Id = 47, SymbolToken = "5610" },
                new Stock { Ticker = "ASTRAL-EQ", Exchange = "NSE", Name = "ASTRAL-EQ", Id = 48, SymbolToken = "14418" },
                new Stock { Ticker = "ATUL-EQ", Exchange = "NSE", Name = "ATUL-EQ", Id = 49, SymbolToken = "263" },
                new Stock { Ticker = "AUROPHARMA-EQ", Exchange = "NSE", Name = "AUROPHARMA-EQ", Id = 50, SymbolToken = "275" },
                new Stock { Ticker = "AVANTIFEED-EQ", Exchange = "NSE", Name = "AVANTIFEED-EQ", Id = 51, SymbolToken = "7936" },
                new Stock { Ticker = "DMART-EQ", Exchange = "NSE", Name = "DMART-EQ", Id = 52, SymbolToken = "19913" },
                new Stock { Ticker = "AXISBANK-EQ", Exchange = "NSE", Name = "AXISBANK-EQ", Id = 53, SymbolToken = "5900" },
                new Stock { Ticker = "BASF-EQ", Exchange = "NSE", Name = "BASF-EQ", Id = 54, SymbolToken = "368" },
                new Stock { Ticker = "BEML-EQ", Exchange = "NSE", Name = "BEML-EQ", Id = 55, SymbolToken = "395" },
                new Stock { Ticker = "BLS-EQ", Exchange = "NSE", Name = "BLS-EQ", Id = 56, SymbolToken = "17279" },
                new Stock { Ticker = "BSE-EQ", Exchange = "NSE", Name = "BSE-EQ", Id = 57, SymbolToken = "19585" },
                new Stock { Ticker = "BAJAJ-AUTO-EQ", Exchange = "NSE", Name = "BAJAJ-AUTO-EQ", Id = 58, SymbolToken = "16669" },
                new Stock { Ticker = "BAJFINANCE-EQ", Exchange = "NSE", Name = "BAJFINANCE-EQ", Id = 59, SymbolToken = "317" },
                new Stock { Ticker = "BAJAJFINSV-EQ", Exchange = "NSE", Name = "BAJAJFINSV-EQ", Id = 60, SymbolToken = "16675" },
                new Stock { Ticker = "BAJAJHLDNG-EQ", Exchange = "NSE", Name = "BAJAJHLDNG-EQ", Id = 61, SymbolToken = "305" },
                new Stock { Ticker = "BALAMINES-EQ", Exchange = "NSE", Name = "BALAMINES-EQ", Id = 62, SymbolToken = "14501" },
                new Stock { Ticker = "BALKRISIND-EQ", Exchange = "NSE", Name = "BALKRISIND-EQ", Id = 63, SymbolToken = "335" },
                new Stock { Ticker = "BALRAMCHIN-EQ", Exchange = "NSE", Name = "BALRAMCHIN-EQ", Id = 64, SymbolToken = "341" },
                new Stock { Ticker = "BANDHANBNK-EQ", Exchange = "NSE", Name = "BANDHANBNK-EQ", Id = 65, SymbolToken = "2263" },
                new Stock { Ticker = "BANKBARODA-EQ", Exchange = "NSE", Name = "BANKBARODA-EQ", Id = 66, SymbolToken = "4668" },
                new Stock { Ticker = "BANKINDIA-EQ", Exchange = "NSE", Name = "BANKINDIA-EQ", Id = 67, SymbolToken = "4745" },
                new Stock { Ticker = "MAHABANK-EQ", Exchange = "NSE", Name = "MAHABANK-EQ", Id = 68, SymbolToken = "11377" },
                new Stock { Ticker = "BATAINDIA-EQ", Exchange = "NSE", Name = "BATAINDIA-EQ", Id = 69, SymbolToken = "371" },
                new Stock { Ticker = "BAYERCROP-EQ", Exchange = "NSE", Name = "BAYERCROP-EQ", Id = 70, SymbolToken = "17927" },
                new Stock { Ticker = "BERGEPAINT-EQ", Exchange = "NSE", Name = "BERGEPAINT-EQ", Id = 71, SymbolToken = "404" },
                new Stock { Ticker = "BDL-EQ", Exchange = "NSE", Name = "BDL-EQ", Id = 72, SymbolToken = "2144" },
                new Stock { Ticker = "BEL-EQ", Exchange = "NSE", Name = "BEL-EQ", Id = 73, SymbolToken = "383" },
                new Stock { Ticker = "BHARATFORG-EQ", Exchange = "NSE", Name = "BHARATFORG-EQ", Id = 74, SymbolToken = "422" },
                new Stock { Ticker = "BHEL-EQ", Exchange = "NSE", Name = "BHEL-EQ", Id = 75, SymbolToken = "438" },
                new Stock { Ticker = "BPCL-EQ", Exchange = "NSE", Name = "BPCL-EQ", Id = 76, SymbolToken = "526" },
                new Stock { Ticker = "BHARTIARTL-EQ", Exchange = "NSE", Name = "BHARTIARTL-EQ", Id = 77, SymbolToken = "10604" },
                new Stock { Ticker = "BHARTIHEXA-EQ", Exchange = "NSE", Name = "BHARTIHEXA-EQ", Id = 78, SymbolToken = "23489" },
                new Stock { Ticker = "BIKAJI-EQ", Exchange = "NSE", Name = "BIKAJI-EQ", Id = 79, SymbolToken = "11966" },
                new Stock { Ticker = "BIOCON-EQ", Exchange = "NSE", Name = "BIOCON-EQ", Id = 80, SymbolToken = "11373" },
                new Stock { Ticker = "BIRLACORPN-EQ", Exchange = "NSE", Name = "BIRLACORPN-EQ", Id = 81, SymbolToken = "480" },
                new Stock { Ticker = "BSOFT-EQ", Exchange = "NSE", Name = "BSOFT-EQ", Id = 82, SymbolToken = "6994" },
                new Stock { Ticker = "BLUEDART-EQ", Exchange = "NSE", Name = "BLUEDART-EQ", Id = 83, SymbolToken = "495" },
                new Stock { Ticker = "BLUESTARCO-EQ", Exchange = "NSE", Name = "BLUESTARCO-EQ", Id = 84, SymbolToken = "8311" },
                new Stock { Ticker = "BBTC-EQ", Exchange = "NSE", Name = "BBTC-EQ", Id = 85, SymbolToken = "380" },
                new Stock { Ticker = "BOSCHLTD-EQ", Exchange = "NSE", Name = "BOSCHLTD-EQ", Id = 86, SymbolToken = "2181" },
                new Stock { Ticker = "BRIGADE-EQ", Exchange = "NSE", Name = "BRIGADE-EQ", Id = 87, SymbolToken = "15184" },
                new Stock { Ticker = "BRITANNIA-EQ", Exchange = "NSE", Name = "BRITANNIA-EQ", Id = 88, SymbolToken = "547" },
                new Stock { Ticker = "MAPMYINDIA-EQ", Exchange = "NSE", Name = "MAPMYINDIA-EQ", Id = 89, SymbolToken = "7227" },
                new Stock { Ticker = "CCL-EQ", Exchange = "NSE", Name = "CCL-EQ", Id = 90, SymbolToken = "11452" },
                new Stock { Ticker = "CESC-EQ", Exchange = "NSE", Name = "CESC-EQ", Id = 91, SymbolToken = "628" },
                new Stock { Ticker = "CGPOWER-EQ", Exchange = "NSE", Name = "CGPOWER-EQ", Id = 92, SymbolToken = "760" },
                new Stock { Ticker = "CIEINDIA-EQ", Exchange = "NSE", Name = "CIEINDIA-EQ", Id = 93, SymbolToken = "14937" },
                new Stock { Ticker = "CRISIL-EQ", Exchange = "NSE", Name = "CRISIL-EQ", Id = 94, SymbolToken = "757" },
                new Stock { Ticker = "CAMPUS-EQ", Exchange = "NSE", Name = "CAMPUS-EQ", Id = 95, SymbolToken = "9362" },
                new Stock { Ticker = "CANFINHOME-EQ", Exchange = "NSE", Name = "CANFINHOME-EQ", Id = 96, SymbolToken = "583" },
                new Stock { Ticker = "CANBK-EQ", Exchange = "NSE", Name = "CANBK-EQ", Id = 97, SymbolToken = "10794" },
                new Stock { Ticker = "CAPLIPOINT-EQ", Exchange = "NSE", Name = "CAPLIPOINT-EQ", Id = 98, SymbolToken = "3906" },
                new Stock { Ticker = "CGCL-EQ", Exchange = "NSE", Name = "CGCL-EQ", Id = 99, SymbolToken = "20329" },
                new Stock { Ticker = "CARBORUNIV-EQ", Exchange = "NSE", Name = "CARBORUNIV-EQ", Id = 100, SymbolToken = "595" },
                new Stock { Ticker = "CASTROLIND-EQ", Exchange = "NSE", Name = "CASTROLIND-EQ", Id = 101, SymbolToken = "1250" },
                new Stock { Ticker = "CEATLTD-EQ", Exchange = "NSE", Name = "CEATLTD-EQ", Id = 102, SymbolToken = "15254" },
                new Stock { Ticker = "CELLO-EQ", Exchange = "NSE", Name = "CELLO-EQ", Id = 103, SymbolToken = "19795" },
                new Stock { Ticker = "CENTRALBK-EQ", Exchange = "NSE", Name = "CENTRALBK-EQ", Id = 104, SymbolToken = "14894" },
                new Stock { Ticker = "CDSL-EQ", Exchange = "NSE", Name = "CDSL-EQ", Id = 105, SymbolToken = "21174" },
                new Stock { Ticker = "CENTURYPLY-EQ", Exchange = "NSE", Name = "CENTURYPLY-EQ", Id = 106, SymbolToken = "13305" },
                new Stock { Ticker = "CERA-EQ", Exchange = "NSE", Name = "CERA-EQ", Id = 107, SymbolToken = "15039" },
                new Stock { Ticker = "CHALET-EQ", Exchange = "NSE", Name = "CHALET-EQ", Id = 108, SymbolToken = "8546" },
                new Stock { Ticker = "CHAMBLFERT-EQ", Exchange = "NSE", Name = "CHAMBLFERT-EQ", Id = 109, SymbolToken = "637" },
                new Stock { Ticker = "CHEMPLASTS-EQ", Exchange = "NSE", Name = "CHEMPLASTS-EQ", Id = 110, SymbolToken = "5449" },
                new Stock { Ticker = "CHENNPETRO-EQ", Exchange = "NSE", Name = "CHENNPETRO-EQ", Id = 111, SymbolToken = "2049" },
                new Stock { Ticker = "CHOLAHLDNG-EQ", Exchange = "NSE", Name = "CHOLAHLDNG-EQ", Id = 112, SymbolToken = "21740" },
                new Stock { Ticker = "CHOLAFIN-EQ", Exchange = "NSE", Name = "CHOLAFIN-EQ", Id = 113, SymbolToken = "685" },
                new Stock { Ticker = "CIPLA-EQ", Exchange = "NSE", Name = "CIPLA-EQ", Id = 114, SymbolToken = "694" },
                new Stock { Ticker = "CUB-EQ", Exchange = "NSE", Name = "CUB-EQ", Id = 115, SymbolToken = "5701" },
                new Stock { Ticker = "CLEAN-EQ", Exchange = "NSE", Name = "CLEAN-EQ", Id = 116, SymbolToken = "5049" },
                new Stock { Ticker = "COALINDIA-EQ", Exchange = "NSE", Name = "COALINDIA-EQ", Id = 117, SymbolToken = "20374" },
                new Stock { Ticker = "COCHINSHIP-EQ", Exchange = "NSE", Name = "COCHINSHIP-EQ", Id = 118, SymbolToken = "21508" },
                new Stock { Ticker = "COFORGE-EQ", Exchange = "NSE", Name = "COFORGE-EQ", Id = 119, SymbolToken = "11543" },
                new Stock { Ticker = "COLPAL-EQ", Exchange = "NSE", Name = "COLPAL-EQ", Id = 120, SymbolToken = "15141" },
                new Stock { Ticker = "CAMS-EQ", Exchange = "NSE", Name = "CAMS-EQ", Id = 121, SymbolToken = "342" },
                new Stock { Ticker = "CONCORDBIO-EQ", Exchange = "NSE", Name = "CONCORDBIO-EQ", Id = 122, SymbolToken = "18060" },
                new Stock { Ticker = "CONCOR-EQ", Exchange = "NSE", Name = "CONCOR-EQ", Id = 123, SymbolToken = "4749" },
                new Stock { Ticker = "COROMANDEL-EQ", Exchange = "NSE", Name = "COROMANDEL-EQ", Id = 124, SymbolToken = "739" },
                new Stock { Ticker = "CRAFTSMAN-EQ", Exchange = "NSE", Name = "CRAFTSMAN-EQ", Id = 125, SymbolToken = "2854" },
                new Stock { Ticker = "CREDITACC-EQ", Exchange = "NSE", Name = "CREDITACC-EQ", Id = 126, SymbolToken = "4421" },
                new Stock { Ticker = "CROMPTON-EQ", Exchange = "NSE", Name = "CROMPTON-EQ", Id = 127, SymbolToken = "17094" },
                new Stock { Ticker = "CUMMINSIND-EQ", Exchange = "NSE", Name = "CUMMINSIND-EQ", Id = 128, SymbolToken = "1901" },
                new Stock { Ticker = "CYIENT-EQ", Exchange = "NSE", Name = "CYIENT-EQ", Id = 129, SymbolToken = "5748" },
                new Stock { Ticker = "DLF-EQ", Exchange = "NSE", Name = "DLF-EQ", Id = 130, SymbolToken = "14732" },
                new Stock { Ticker = "DOMS-EQ", Exchange = "NSE", Name = "DOMS-EQ", Id = 131, SymbolToken = "20551" },
                new Stock { Ticker = "DABUR-EQ", Exchange = "NSE", Name = "DABUR-EQ", Id = 132, SymbolToken = "772" },
                new Stock { Ticker = "DALBHARAT-EQ", Exchange = "NSE", Name = "DALBHARAT-EQ", Id = 133, SymbolToken = "8075" },
                new Stock { Ticker = "DATAPATTNS-EQ", Exchange = "NSE", Name = "DATAPATTNS-EQ", Id = 134, SymbolToken = "7358" },
                new Stock { Ticker = "DEEPAKFERT-EQ", Exchange = "NSE", Name = "DEEPAKFERT-EQ", Id = 135, SymbolToken = "827" },
                new Stock { Ticker = "DEEPAKNTR-EQ", Exchange = "NSE", Name = "DEEPAKNTR-EQ", Id = 136, SymbolToken = "19943" },
                new Stock { Ticker = "DELHIVERY-EQ", Exchange = "NSE", Name = "DELHIVERY-EQ", Id = 137, SymbolToken = "9599" },
                new Stock { Ticker = "DEVYANI-EQ", Exchange = "NSE", Name = "DEVYANI-EQ", Id = 138, SymbolToken = "5373" },
                new Stock { Ticker = "DIVISLAB-EQ", Exchange = "NSE", Name = "DIVISLAB-EQ", Id = 139, SymbolToken = "10940" },
                new Stock { Ticker = "DIXON-EQ", Exchange = "NSE", Name = "DIXON-EQ", Id = 140, SymbolToken = "21690" },
                new Stock { Ticker = "LALPATHLAB-EQ", Exchange = "NSE", Name = "LALPATHLAB-EQ", Id = 141, SymbolToken = "11654" },
                new Stock { Ticker = "DRREDDY-EQ", Exchange = "NSE", Name = "DRREDDY-EQ", Id = 142, SymbolToken = "881" },
                new Stock { Ticker = "EIDPARRY-EQ", Exchange = "NSE", Name = "EIDPARRY-EQ", Id = 143, SymbolToken = "916" },
                new Stock { Ticker = "EIHOTEL-EQ", Exchange = "NSE", Name = "EIHOTEL-EQ", Id = 144, SymbolToken = "919" },
                new Stock { Ticker = "EASEMYTRIP-EQ", Exchange = "NSE", Name = "EASEMYTRIP-EQ", Id = 145, SymbolToken = "2792" },
                new Stock { Ticker = "EICHERMOT-EQ", Exchange = "NSE", Name = "EICHERMOT-EQ", Id = 146, SymbolToken = "910" },
                new Stock { Ticker = "ELECON-EQ", Exchange = "NSE", Name = "ELECON-EQ", Id = 147, SymbolToken = "13643" },
                new Stock { Ticker = "ELGIEQUIP-EQ", Exchange = "NSE", Name = "ELGIEQUIP-EQ", Id = 148, SymbolToken = "937" },
                new Stock { Ticker = "EMAMILTD-EQ", Exchange = "NSE", Name = "EMAMILTD-EQ", Id = 149, SymbolToken = "13517" },
                new Stock { Ticker = "EMCURE-EQ", Exchange = "NSE", Name = "EMCURE-EQ", Id = 150, SymbolToken = "24398" },
                new Stock { Ticker = "ENDURANCE-EQ", Exchange = "NSE", Name = "ENDURANCE-EQ", Id = 151, SymbolToken = "18822" },
                new Stock { Ticker = "ENGINERSIN-EQ", Exchange = "NSE", Name = "ENGINERSIN-EQ", Id = 152, SymbolToken = "4907" },
                new Stock { Ticker = "EQUITASBNK-EQ", Exchange = "NSE", Name = "EQUITASBNK-EQ", Id = 153, SymbolToken = "913" },
                new Stock { Ticker = "ERIS-EQ", Exchange = "NSE", Name = "ERIS-EQ", Id = 154, SymbolToken = "21154" },
                new Stock { Ticker = "ESCORTS-EQ", Exchange = "NSE", Name = "ESCORTS-EQ", Id = 155, SymbolToken = "958" },
                new Stock { Ticker = "EXIDEIND-EQ", Exchange = "NSE", Name = "EXIDEIND-EQ", Id = 156, SymbolToken = "676" },
                new Stock { Ticker = "NYKAA-EQ", Exchange = "NSE", Name = "NYKAA-EQ", Id = 157, SymbolToken = "6545" },
                new Stock { Ticker = "FEDERALBNK-EQ", Exchange = "NSE", Name = "FEDERALBNK-EQ", Id = 158, SymbolToken = "1023" },
                new Stock { Ticker = "FACT-EQ", Exchange = "NSE", Name = "FACT-EQ", Id = 159, SymbolToken = "1008" },
                new Stock { Ticker = "FINEORG-EQ", Exchange = "NSE", Name = "FINEORG-EQ", Id = 160, SymbolToken = "3744" },
                new Stock { Ticker = "FINCABLES-EQ", Exchange = "NSE", Name = "FINCABLES-EQ", Id = 161, SymbolToken = "1038" },
                new Stock { Ticker = "FINPIPE-EQ", Exchange = "NSE", Name = "FINPIPE-EQ", Id = 162, SymbolToken = "1041" },
                new Stock { Ticker = "FSL-EQ", Exchange = "NSE", Name = "FSL-EQ", Id = 163, SymbolToken = "14304" },
                new Stock { Ticker = "FIVESTAR-EQ", Exchange = "NSE", Name = "FIVESTAR-EQ", Id = 164, SymbolToken = "12032" },
                new Stock { Ticker = "FORTIS-EQ", Exchange = "NSE", Name = "FORTIS-EQ", Id = 165, SymbolToken = "14592" },
                new Stock { Ticker = "GRINFRA-EQ", Exchange = "NSE", Name = "GRINFRA-EQ", Id = 166, SymbolToken = "5054" },
                new Stock { Ticker = "GAIL-EQ", Exchange = "NSE", Name = "GAIL-EQ", Id = 167, SymbolToken = "4717" },
                new Stock { Ticker = "GVT%26D-EQ", Exchange = "NSE", Name = "GVT%26D-EQ", Id = 168, SymbolToken = "16783" },
                new Stock { Ticker = "GMRAIRPORT-EQ", Exchange = "NSE", Name = "GMRAIRPORT-EQ", Id = 169, SymbolToken = "13528" },
                new Stock { Ticker = "GRSE-EQ", Exchange = "NSE", Name = "GRSE-EQ", Id = 170, SymbolToken = "5475" },
                new Stock { Ticker = "GICRE-EQ", Exchange = "NSE", Name = "GICRE-EQ", Id = 171, SymbolToken = "277" },
                new Stock { Ticker = "GILLETTE-EQ", Exchange = "NSE", Name = "GILLETTE-EQ", Id = 172, SymbolToken = "1576" },
                new Stock { Ticker = "GLAND-EQ", Exchange = "NSE", Name = "GLAND-EQ", Id = 173, SymbolToken = "1186" },
                new Stock { Ticker = "GLAXO-EQ", Exchange = "NSE", Name = "GLAXO-EQ", Id = 174, SymbolToken = "1153" },
                new Stock { Ticker = "GLENMARK-EQ", Exchange = "NSE", Name = "GLENMARK-EQ", Id = 175, SymbolToken = "7406" },
                new Stock { Ticker = "MEDANTA-EQ", Exchange = "NSE", Name = "MEDANTA-EQ", Id = 176, SymbolToken = "11956" },
                new Stock { Ticker = "GODIGIT-EQ", Exchange = "NSE", Name = "GODIGIT-EQ", Id = 177, SymbolToken = "23799" },
                new Stock { Ticker = "GPIL-EQ", Exchange = "NSE", Name = "GPIL-EQ", Id = 178, SymbolToken = "13409" },
                new Stock { Ticker = "GODFRYPHLP-EQ", Exchange = "NSE", Name = "GODFRYPHLP-EQ", Id = 179, SymbolToken = "1181" },
                new Stock { Ticker = "GODREJAGRO-EQ", Exchange = "NSE", Name = "GODREJAGRO-EQ", Id = 180, SymbolToken = "144" },
                new Stock { Ticker = "GODREJCP-EQ", Exchange = "NSE", Name = "GODREJCP-EQ", Id = 181, SymbolToken = "10099" },
                new Stock { Ticker = "GODREJIND-EQ", Exchange = "NSE", Name = "GODREJIND-EQ", Id = 182, SymbolToken = "10925" },
                new Stock { Ticker = "GODREJPROP-EQ", Exchange = "NSE", Name = "GODREJPROP-EQ", Id = 183, SymbolToken = "17875" },
                new Stock { Ticker = "GRANULES-EQ", Exchange = "NSE", Name = "GRANULES-EQ", Id = 184, SymbolToken = "11872" },
                new Stock { Ticker = "GRAPHITE-EQ", Exchange = "NSE", Name = "GRAPHITE-EQ", Id = 185, SymbolToken = "592" },
                new Stock { Ticker = "GRASIM-EQ", Exchange = "NSE", Name = "GRASIM-EQ", Id = 186, SymbolToken = "1232" },
                new Stock { Ticker = "GESHIP-EQ", Exchange = "NSE", Name = "GESHIP-EQ", Id = 187, SymbolToken = "13776" },
                new Stock { Ticker = "GRINDWELL-EQ", Exchange = "NSE", Name = "GRINDWELL-EQ", Id = 188, SymbolToken = "13560" },
                new Stock { Ticker = "GAEL-EQ", Exchange = "NSE", Name = "GAEL-EQ", Id = 189, SymbolToken = "8828" },
                new Stock { Ticker = "FLUOROCHEM-EQ", Exchange = "NSE", Name = "FLUOROCHEM-EQ", Id = 190, SymbolToken = "13750" },
                new Stock { Ticker = "GUJGASLTD-EQ", Exchange = "NSE", Name = "GUJGASLTD-EQ", Id = 191, SymbolToken = "10599" },
                new Stock { Ticker = "GMDCLTD-EQ", Exchange = "NSE", Name = "GMDCLTD-EQ", Id = 192, SymbolToken = "5204" },
                new Stock { Ticker = "GNFC-EQ", Exchange = "NSE", Name = "GNFC-EQ", Id = 193, SymbolToken = "1174" },
                new Stock { Ticker = "GPPL-EQ", Exchange = "NSE", Name = "GPPL-EQ", Id = 194, SymbolToken = "19731" },
                new Stock { Ticker = "GSFC-EQ", Exchange = "NSE", Name = "GSFC-EQ", Id = 195, SymbolToken = "1247" },
                new Stock { Ticker = "GSPL-EQ", Exchange = "NSE", Name = "GSPL-EQ", Id = 196, SymbolToken = "13197" },
                new Stock { Ticker = "HEG-EQ", Exchange = "NSE", Name = "HEG-EQ", Id = 197, SymbolToken = "1336" },
                new Stock { Ticker = "HBLENGINE-EQ", Exchange = "NSE", Name = "HBLENGINE-EQ", Id = 198, SymbolToken = "13966" },
                new Stock { Ticker = "HCLTECH-EQ", Exchange = "NSE", Name = "HCLTECH-EQ", Id = 199, SymbolToken = "7229" },
                new Stock { Ticker = "HDFCAMC-EQ", Exchange = "NSE", Name = "HDFCAMC-EQ", Id = 200, SymbolToken = "4244" },
                new Stock { Ticker = "HDFCBANK-EQ", Exchange = "NSE", Name = "HDFCBANK-EQ", Id = 201, SymbolToken = "1333" },
                new Stock { Ticker = "HDFCLIFE-EQ", Exchange = "NSE", Name = "HDFCLIFE-EQ", Id = 202, SymbolToken = "467" },
                new Stock { Ticker = "HFCL-EQ", Exchange = "NSE", Name = "HFCL-EQ", Id = 203, SymbolToken = "21951" },
                new Stock { Ticker = "HAPPSTMNDS-EQ", Exchange = "NSE", Name = "HAPPSTMNDS-EQ", Id = 204, SymbolToken = "48" },
                new Stock { Ticker = "HAVELLS-EQ", Exchange = "NSE", Name = "HAVELLS-EQ", Id = 205, SymbolToken = "9819" },
                new Stock { Ticker = "HEROMOTOCO-EQ", Exchange = "NSE", Name = "HEROMOTOCO-EQ", Id = 206, SymbolToken = "1348" },
                new Stock { Ticker = "HSCL-EQ", Exchange = "NSE", Name = "HSCL-EQ", Id = 207, SymbolToken = "14334" },
                new Stock { Ticker = "HINDALCO-EQ", Exchange = "NSE", Name = "HINDALCO-EQ", Id = 208, SymbolToken = "1363" },
                new Stock { Ticker = "HAL-EQ", Exchange = "NSE", Name = "HAL-EQ", Id = 209, SymbolToken = "2303" },
                new Stock { Ticker = "HINDCOPPER-EQ", Exchange = "NSE", Name = "HINDCOPPER-EQ", Id = 210, SymbolToken = "17939" },
                new Stock { Ticker = "HINDPETRO-EQ", Exchange = "NSE", Name = "HINDPETRO-EQ", Id = 211, SymbolToken = "1406" },
                new Stock { Ticker = "HINDUNILVR-EQ", Exchange = "NSE", Name = "HINDUNILVR-EQ", Id = 212, SymbolToken = "1394" },
                new Stock { Ticker = "HINDZINC-EQ", Exchange = "NSE", Name = "HINDZINC-EQ", Id = 213, SymbolToken = "1424" },
                new Stock { Ticker = "POWERINDIA-EQ", Exchange = "NSE", Name = "POWERINDIA-EQ", Id = 214, SymbolToken = "18457" },
                new Stock { Ticker = "HOMEFIRST-EQ", Exchange = "NSE", Name = "HOMEFIRST-EQ", Id = 215, SymbolToken = "2056" },
                new Stock { Ticker = "HONASA-EQ", Exchange = "NSE", Name = "HONASA-EQ", Id = 216, SymbolToken = "19813" },
                new Stock { Ticker = "HONAUT-EQ", Exchange = "NSE", Name = "HONAUT-EQ", Id = 217, SymbolToken = "3417" },
                new Stock { Ticker = "HUDCO-EQ", Exchange = "NSE", Name = "HUDCO-EQ", Id = 218, SymbolToken = "20825" },
                new Stock { Ticker = "ICICIBANK-EQ", Exchange = "NSE", Name = "ICICIBANK-EQ", Id = 219, SymbolToken = "4963" },
                new Stock { Ticker = "ICICIGI-EQ", Exchange = "NSE", Name = "ICICIGI-EQ", Id = 220, SymbolToken = "21770" },
                new Stock { Ticker = "ICICIPRULI-EQ", Exchange = "NSE", Name = "ICICIPRULI-EQ", Id = 221, SymbolToken = "18652" },
                new Stock { Ticker = "ISEC-EQ", Exchange = "NSE", Name = "ISEC-EQ", Id = 222, SymbolToken = "2489" },
                new Stock { Ticker = "IDBI-EQ", Exchange = "NSE", Name = "IDBI-EQ", Id = 223, SymbolToken = "1476" },
                new Stock { Ticker = "IDFCFIRSTB-EQ", Exchange = "NSE", Name = "IDFCFIRSTB-EQ", Id = 224, SymbolToken = "11184" },
                new Stock { Ticker = "IFCI-EQ", Exchange = "NSE", Name = "IFCI-EQ", Id = 225, SymbolToken = "1491" },
                new Stock { Ticker = "IIFL-EQ", Exchange = "NSE", Name = "IIFL-EQ", Id = 226, SymbolToken = "11809" },
                new Stock { Ticker = "INOXINDIA-EQ", Exchange = "NSE", Name = "INOXINDIA-EQ", Id = 227, SymbolToken = "20607" },
                new Stock { Ticker = "IRB-EQ", Exchange = "NSE", Name = "IRB-EQ", Id = 228, SymbolToken = "15313" },
                new Stock { Ticker = "IRCON-EQ", Exchange = "NSE", Name = "IRCON-EQ", Id = 229, SymbolToken = "4986" },
                new Stock { Ticker = "ITC-EQ", Exchange = "NSE", Name = "ITC-EQ", Id = 230, SymbolToken = "1660" },
                //new Stock { Ticker = "ITI-EQ", Exchange = "NSE", Name = "ITI-EQ", Id = 231, SymbolToken = "" },
                new Stock { Ticker = "INDGN-EQ", Exchange = "NSE", Name = "INDGN-EQ", Id = 232, SymbolToken = "23693" },
                new Stock { Ticker = "INDIACEM-EQ", Exchange = "NSE", Name = "INDIACEM-EQ", Id = 233, SymbolToken = "1515" },
                new Stock { Ticker = "INDIAMART-EQ", Exchange = "NSE", Name = "INDIAMART-EQ", Id = 234, SymbolToken = "10726" },
                new Stock { Ticker = "INDIANB-EQ", Exchange = "NSE", Name = "INDIANB-EQ", Id = 235, SymbolToken = "14309" },
                new Stock { Ticker = "IEX-EQ", Exchange = "NSE", Name = "IEX-EQ", Id = 236, SymbolToken = "220" },
                new Stock { Ticker = "INDHOTEL-EQ", Exchange = "NSE", Name = "INDHOTEL-EQ", Id = 237, SymbolToken = "1512" },
                new Stock { Ticker = "IOC-EQ", Exchange = "NSE", Name = "IOC-EQ", Id = 238, SymbolToken = "1624" },
                new Stock { Ticker = "IOB-EQ", Exchange = "NSE", Name = "IOB-EQ", Id = 239, SymbolToken = "9348" },
                new Stock { Ticker = "IRCTC-EQ", Exchange = "NSE", Name = "IRCTC-EQ", Id = 240, SymbolToken = "13611" },
                new Stock { Ticker = "IRFC-EQ", Exchange = "NSE", Name = "IRFC-EQ", Id = 241, SymbolToken = "2029" },
                new Stock { Ticker = "IREDA-EQ", Exchange = "NSE", Name = "IREDA-EQ", Id = 242, SymbolToken = "20261" },
                new Stock { Ticker = "IGL-EQ", Exchange = "NSE", Name = "IGL-EQ", Id = 243, SymbolToken = "11262" },
                new Stock { Ticker = "INDUSTOWER-EQ", Exchange = "NSE", Name = "INDUSTOWER-EQ", Id = 244, SymbolToken = "29135" },
                new Stock { Ticker = "INDUSINDBK-EQ", Exchange = "NSE", Name = "INDUSINDBK-EQ", Id = 245, SymbolToken = "5258" },
                new Stock { Ticker = "NAUKRI-EQ", Exchange = "NSE", Name = "NAUKRI-EQ", Id = 246, SymbolToken = "13751" },
                new Stock { Ticker = "INFY-EQ", Exchange = "NSE", Name = "INFY-EQ", Id = 247, SymbolToken = "1594" },
                new Stock { Ticker = "INOXWIND-EQ", Exchange = "NSE", Name = "INOXWIND-EQ", Id = 248, SymbolToken = "7852" },
                new Stock { Ticker = "INTELLECT-EQ", Exchange = "NSE", Name = "INTELLECT-EQ", Id = 249, SymbolToken = "5926" },
                new Stock { Ticker = "INDIGO-EQ", Exchange = "NSE", Name = "INDIGO-EQ", Id = 250, SymbolToken = "11195" },
                new Stock { Ticker = "IPCALAB-EQ", Exchange = "NSE", Name = "IPCALAB-EQ", Id = 251, SymbolToken = "1633" },
                new Stock { Ticker = "JBCHEPHARM-EQ", Exchange = "NSE", Name = "JBCHEPHARM-EQ", Id = 252, SymbolToken = "1726" },
                new Stock { Ticker = "JKCEMENT-EQ", Exchange = "NSE", Name = "JKCEMENT-EQ", Id = 253, SymbolToken = "13270" },
                new Stock { Ticker = "JBMA-EQ", Exchange = "NSE", Name = "JBMA-EQ", Id = 254, SymbolToken = "11655" },
                new Stock { Ticker = "JKLAKSHMI-EQ", Exchange = "NSE", Name = "JKLAKSHMI-EQ", Id = 255, SymbolToken = "13491" },
                new Stock { Ticker = "JKTYRE-EQ", Exchange = "NSE", Name = "JKTYRE-EQ", Id = 256, SymbolToken = "14435" },
                new Stock { Ticker = "JMFINANCIL-EQ", Exchange = "NSE", Name = "JMFINANCIL-EQ", Id = 257, SymbolToken = "13637" },
                new Stock { Ticker = "JSWENERGY-EQ", Exchange = "NSE", Name = "JSWENERGY-EQ", Id = 258, SymbolToken = "17869" },
                new Stock { Ticker = "JSWINFRA-EQ", Exchange = "NSE", Name = "JSWINFRA-EQ", Id = 259, SymbolToken = "19020" },
                new Stock { Ticker = "JSWSTEEL-EQ", Exchange = "NSE", Name = "JSWSTEEL-EQ", Id = 260, SymbolToken = "11723" },
                new Stock { Ticker = "JPPOWER-EQ", Exchange = "NSE", Name = "JPPOWER-EQ", Id = 261, SymbolToken = "11763" },
                new Stock { Ticker = "J%26KBANK-EQ", Exchange = "NSE", Name = "J%26KBANK-EQ", Id = 262, SymbolToken = "5633" },
                new Stock { Ticker = "JINDALSAW-EQ", Exchange = "NSE", Name = "JINDALSAW-EQ", Id = 263, SymbolToken = "3024" },
                new Stock { Ticker = "JSL-EQ", Exchange = "NSE", Name = "JSL-EQ", Id = 264, SymbolToken = "11236" },
                new Stock { Ticker = "JINDALSTEL-EQ", Exchange = "NSE", Name = "JINDALSTEL-EQ", Id = 265, SymbolToken = "6733" },
                new Stock { Ticker = "JIOFIN-EQ", Exchange = "NSE", Name = "JIOFIN-EQ", Id = 266, SymbolToken = "18143" },
                new Stock { Ticker = "JUBLFOOD-EQ", Exchange = "NSE", Name = "JUBLFOOD-EQ", Id = 267, SymbolToken = "18096" },
                new Stock { Ticker = "JUBLINGREA-EQ", Exchange = "NSE", Name = "JUBLINGREA-EQ", Id = 268, SymbolToken = "2783" },
                new Stock { Ticker = "JUBLPHARMA-EQ", Exchange = "NSE", Name = "JUBLPHARMA-EQ", Id = 269, SymbolToken = "3637" },
                new Stock { Ticker = "JWL-EQ", Exchange = "NSE", Name = "JWL-EQ", Id = 270, SymbolToken = "20224" },
                new Stock { Ticker = "JUSTDIAL-EQ", Exchange = "NSE", Name = "JUSTDIAL-EQ", Id = 271, SymbolToken = "29962" },
                new Stock { Ticker = "JYOTHYLAB-EQ", Exchange = "NSE", Name = "JYOTHYLAB-EQ", Id = 272, SymbolToken = "15146" },
                new Stock { Ticker = "JYOTICNC-EQ", Exchange = "NSE", Name = "JYOTICNC-EQ", Id = 273, SymbolToken = "21334" },
                new Stock { Ticker = "KPRMILL-EQ", Exchange = "NSE", Name = "KPRMILL-EQ", Id = 274, SymbolToken = "14912" },
                new Stock { Ticker = "KEI-EQ", Exchange = "NSE", Name = "KEI-EQ", Id = 275, SymbolToken = "13310" },
                new Stock { Ticker = "KNRCON-EQ", Exchange = "NSE", Name = "KNRCON-EQ", Id = 276, SymbolToken = "15283" },
                new Stock { Ticker = "KPITTECH-EQ", Exchange = "NSE", Name = "KPITTECH-EQ", Id = 277, SymbolToken = "9683" },
                new Stock { Ticker = "KSB-EQ", Exchange = "NSE", Name = "KSB-EQ", Id = 278, SymbolToken = "1949" },
                new Stock { Ticker = "KAJARIACER-EQ", Exchange = "NSE", Name = "KAJARIACER-EQ", Id = 279, SymbolToken = "1808" },
                new Stock { Ticker = "KPIL-EQ", Exchange = "NSE", Name = "KPIL-EQ", Id = 280, SymbolToken = "1814" },
                new Stock { Ticker = "KALYANKJIL-EQ", Exchange = "NSE", Name = "KALYANKJIL-EQ", Id = 281, SymbolToken = "2955" },
                new Stock { Ticker = "KANSAINER-EQ", Exchange = "NSE", Name = "KANSAINER-EQ", Id = 282, SymbolToken = "1196" },
                new Stock { Ticker = "KARURVYSYA-EQ", Exchange = "NSE", Name = "KARURVYSYA-EQ", Id = 283, SymbolToken = "1838" },
                new Stock { Ticker = "KAYNES-EQ", Exchange = "NSE", Name = "KAYNES-EQ", Id = 284, SymbolToken = "12092" },
                new Stock { Ticker = "KEC-EQ", Exchange = "NSE", Name = "KEC-EQ", Id = 285, SymbolToken = "1547" },
                new Stock { Ticker = "KFINTECH-EQ", Exchange = "NSE", Name = "KFINTECH-EQ", Id = 286, SymbolToken = "13359" },
                new Stock { Ticker = "KIRLOSBROS-EQ", Exchange = "NSE", Name = "KIRLOSBROS-EQ", Id = 287, SymbolToken = "18581" },
                new Stock { Ticker = "KIRLOSENG-EQ", Exchange = "NSE", Name = "KIRLOSENG-EQ", Id = 288, SymbolToken = "20936" },
                new Stock { Ticker = "KOTAKBANK-EQ", Exchange = "NSE", Name = "KOTAKBANK-EQ", Id = 289, SymbolToken = "1922" },
                new Stock { Ticker = "KIMS-EQ", Exchange = "NSE", Name = "KIMS-EQ", Id = 290, SymbolToken = "4847" },
                new Stock { Ticker = "LTF-EQ", Exchange = "NSE", Name = "LTF-EQ", Id = 291, SymbolToken = "24948" },
                new Stock { Ticker = "LTTS-EQ", Exchange = "NSE", Name = "LTTS-EQ", Id = 292, SymbolToken = "18564" },
                new Stock { Ticker = "LICHSGFIN-EQ", Exchange = "NSE", Name = "LICHSGFIN-EQ", Id = 293, SymbolToken = "1997" },
                new Stock { Ticker = "LTIM-EQ", Exchange = "NSE", Name = "LTIM-EQ", Id = 294, SymbolToken = "17818" },
                new Stock { Ticker = "LT-EQ", Exchange = "NSE", Name = "LT-EQ", Id = 295, SymbolToken = "11483" },
                new Stock { Ticker = "LATENTVIEW-EQ", Exchange = "NSE", Name = "LATENTVIEW-EQ", Id = 296, SymbolToken = "6818" },
                new Stock { Ticker = "LAURUSLABS-EQ", Exchange = "NSE", Name = "LAURUSLABS-EQ", Id = 297, SymbolToken = "19234" },
                new Stock { Ticker = "LEMONTREE-EQ", Exchange = "NSE", Name = "LEMONTREE-EQ", Id = 298, SymbolToken = "2606" },
                new Stock { Ticker = "LICI-EQ", Exchange = "NSE", Name = "LICI-EQ", Id = 299, SymbolToken = "9480" },
                new Stock { Ticker = "LINDEINDIA-EQ", Exchange = "NSE", Name = "LINDEINDIA-EQ", Id = 300, SymbolToken = "1627" },
                new Stock { Ticker = "LLOYDSME-EQ", Exchange = "NSE", Name = "LLOYDSME-EQ", Id = 301, SymbolToken = "17313" },
                new Stock { Ticker = "LUPIN-EQ", Exchange = "NSE", Name = "LUPIN-EQ", Id = 302, SymbolToken = "10440" },
                new Stock { Ticker = "MMTC-EQ", Exchange = "NSE", Name = "MMTC-EQ", Id = 303, SymbolToken = "17957" },
                new Stock { Ticker = "MRF-EQ", Exchange = "NSE", Name = "MRF-EQ", Id = 304, SymbolToken = "2277" },
                new Stock { Ticker = "LODHA-EQ", Exchange = "NSE", Name = "LODHA-EQ", Id = 305, SymbolToken = "3220" },
                new Stock { Ticker = "MGL-EQ", Exchange = "NSE", Name = "MGL-EQ", Id = 306, SymbolToken = "17534" },
                new Stock { Ticker = "MAHSEAMLES-EQ", Exchange = "NSE", Name = "MAHSEAMLES-EQ", Id = 307, SymbolToken = "2088" },
                new Stock { Ticker = "M%26MFIN-EQ", Exchange = "NSE", Name = "M%26MFIN-EQ", Id = 308, SymbolToken = "13285" },
                new Stock { Ticker = "M%26M-EQ", Exchange = "NSE", Name = "M%26M-EQ", Id = 309, SymbolToken = "2031" },
                new Stock { Ticker = "MAHLIFE-EQ", Exchange = "NSE", Name = "MAHLIFE-EQ", Id = 310, SymbolToken = "8050" },
                new Stock { Ticker = "MANAPPURAM-EQ", Exchange = "NSE", Name = "MANAPPURAM-EQ", Id = 311, SymbolToken = "19061" },
                new Stock { Ticker = "MRPL-EQ", Exchange = "NSE", Name = "MRPL-EQ", Id = 312, SymbolToken = "2283" },
                new Stock { Ticker = "MANKIND-EQ", Exchange = "NSE", Name = "MANKIND-EQ", Id = 313, SymbolToken = "15380" },
                new Stock { Ticker = "MARICO-EQ", Exchange = "NSE", Name = "MARICO-EQ", Id = 314, SymbolToken = "4067" },
                new Stock { Ticker = "MARUTI-EQ", Exchange = "NSE", Name = "MARUTI-EQ", Id = 315, SymbolToken = "10999" },
                new Stock { Ticker = "MASTEK-EQ", Exchange = "NSE", Name = "MASTEK-EQ", Id = 316, SymbolToken = "2124" },
                new Stock { Ticker = "MFSL-EQ", Exchange = "NSE", Name = "MFSL-EQ", Id = 317, SymbolToken = "2142" },
                new Stock { Ticker = "MAXHEALTH-EQ", Exchange = "NSE", Name = "MAXHEALTH-EQ", Id = 318, SymbolToken = "22377" },
                new Stock { Ticker = "MAZDOCK-EQ", Exchange = "NSE", Name = "MAZDOCK-EQ", Id = 319, SymbolToken = "509" },
                new Stock { Ticker = "METROBRAND-EQ", Exchange = "NSE", Name = "METROBRAND-EQ", Id = 320, SymbolToken = "7242" },
                new Stock { Ticker = "METROPOLIS-EQ", Exchange = "NSE", Name = "METROPOLIS-EQ", Id = 321, SymbolToken = "9581" },
                new Stock { Ticker = "MINDACORP-EQ", Exchange = "NSE", Name = "MINDACORP-EQ", Id = 322, SymbolToken = "25897" },
                new Stock { Ticker = "MSUMI-EQ", Exchange = "NSE", Name = "MSUMI-EQ", Id = 323, SymbolToken = "8596" },
                new Stock { Ticker = "MOTILALOFS-EQ", Exchange = "NSE", Name = "MOTILALOFS-EQ", Id = 324, SymbolToken = "14947" },
                new Stock { Ticker = "MPHASIS-EQ", Exchange = "NSE", Name = "MPHASIS-EQ", Id = 325, SymbolToken = "4503" },
                new Stock { Ticker = "MCX-EQ", Exchange = "NSE", Name = "MCX-EQ", Id = 326, SymbolToken = "31181" },
                new Stock { Ticker = "MUTHOOTFIN-EQ", Exchange = "NSE", Name = "MUTHOOTFIN-EQ", Id = 327, SymbolToken = "23650" },
                new Stock { Ticker = "NATCOPHARM-EQ", Exchange = "NSE", Name = "NATCOPHARM-EQ", Id = 328, SymbolToken = "3918" },
                new Stock { Ticker = "NBCC-EQ", Exchange = "NSE", Name = "NBCC-EQ", Id = 329, SymbolToken = "31415" },
                new Stock { Ticker = "NCC-EQ", Exchange = "NSE", Name = "NCC-EQ", Id = 330, SymbolToken = "2319" },
                new Stock { Ticker = "NHPC-EQ", Exchange = "NSE", Name = "NHPC-EQ", Id = 331, SymbolToken = "17400" },
                new Stock { Ticker = "NLCINDIA-EQ", Exchange = "NSE", Name = "NLCINDIA-EQ", Id = 332, SymbolToken = "8585" },
                new Stock { Ticker = "NMDC-EQ", Exchange = "NSE", Name = "NMDC-EQ", Id = 333, SymbolToken = "15332" },
                new Stock { Ticker = "NSLNISP-EQ", Exchange = "NSE", Name = "NSLNISP-EQ", Id = 334, SymbolToken = "14180" },
                new Stock { Ticker = "NTPC-EQ", Exchange = "NSE", Name = "NTPC-EQ", Id = 335, SymbolToken = "11630" },
                new Stock { Ticker = "NH-EQ", Exchange = "NSE", Name = "NH-EQ", Id = 336, SymbolToken = "11840" },
                new Stock { Ticker = "NATIONALUM-EQ", Exchange = "NSE", Name = "NATIONALUM-EQ", Id = 337, SymbolToken = "6364" },
                new Stock { Ticker = "NAVINFLUOR-EQ", Exchange = "NSE", Name = "NAVINFLUOR-EQ", Id = 338, SymbolToken = "14672" },
                new Stock { Ticker = "NESTLEIND-EQ", Exchange = "NSE", Name = "NESTLEIND-EQ", Id = 339, SymbolToken = "17963" },
                new Stock { Ticker = "NETWEB-EQ", Exchange = "NSE", Name = "NETWEB-EQ", Id = 340, SymbolToken = "17433" },
                new Stock { Ticker = "NETWORK18-EQ", Exchange = "NSE", Name = "NETWORK18-EQ", Id = 341, SymbolToken = "14111" },
                new Stock { Ticker = "NEWGEN-EQ", Exchange = "NSE", Name = "NEWGEN-EQ", Id = 342, SymbolToken = "1164" },
                new Stock { Ticker = "NAM-INDIA-EQ", Exchange = "NSE", Name = "NAM-INDIA-EQ", Id = 343, SymbolToken = "357" },
                new Stock { Ticker = "NUVAMA-EQ", Exchange = "NSE", Name = "NUVAMA-EQ", Id = 344, SymbolToken = "18721" },
                new Stock { Ticker = "NUVOCO-EQ", Exchange = "NSE", Name = "NUVOCO-EQ", Id = 345, SymbolToken = "5426" },
                new Stock { Ticker = "OBEROIRLTY-EQ", Exchange = "NSE", Name = "OBEROIRLTY-EQ", Id = 346, SymbolToken = "20242" },
                new Stock { Ticker = "ONGC-EQ", Exchange = "NSE", Name = "ONGC-EQ", Id = 347, SymbolToken = "2475" },
                new Stock { Ticker = "OIL-EQ", Exchange = "NSE", Name = "OIL-EQ", Id = 348, SymbolToken = "17438" },
                new Stock { Ticker = "OLECTRA-EQ", Exchange = "NSE", Name = "OLECTRA-EQ", Id = 349, SymbolToken = "10637" },
                new Stock { Ticker = "PAYTM-EQ", Exchange = "NSE", Name = "PAYTM-EQ", Id = 350, SymbolToken = "6705" },
                new Stock { Ticker = "OFSS-EQ", Exchange = "NSE", Name = "OFSS-EQ", Id = 351, SymbolToken = "10738" },
                new Stock { Ticker = "POLICYBZR-EQ", Exchange = "NSE", Name = "POLICYBZR-EQ", Id = 352, SymbolToken = "6656" },
                new Stock { Ticker = "PCBL-EQ", Exchange = "NSE", Name = "PCBL-EQ", Id = 353, SymbolToken = "2649" },
                new Stock { Ticker = "PIIND-EQ", Exchange = "NSE", Name = "PIIND-EQ", Id = 354, SymbolToken = "24184" },
                new Stock { Ticker = "PNBHOUSING-EQ", Exchange = "NSE", Name = "PNBHOUSING-EQ", Id = 355, SymbolToken = "18908" },
                new Stock { Ticker = "PNCINFRA-EQ", Exchange = "NSE", Name = "PNCINFRA-EQ", Id = 356, SymbolToken = "9385" },
                new Stock { Ticker = "PTCIL-EQ", Exchange = "NSE", Name = "PTCIL-EQ", Id = 357, SymbolToken = "16682" },
                new Stock { Ticker = "PVRINOX-EQ", Exchange = "NSE", Name = "PVRINOX-EQ", Id = 358, SymbolToken = "13147" },
                new Stock { Ticker = "PAGEIND-EQ", Exchange = "NSE", Name = "PAGEIND-EQ", Id = 359, SymbolToken = "14413" },
                new Stock { Ticker = "PATANJALI-EQ", Exchange = "NSE", Name = "PATANJALI-EQ", Id = 360, SymbolToken = "17029" },
                new Stock { Ticker = "PERSISTENT-EQ", Exchange = "NSE", Name = "PERSISTENT-EQ", Id = 361, SymbolToken = "18365" },
                new Stock { Ticker = "PETRONET-EQ", Exchange = "NSE", Name = "PETRONET-EQ", Id = 362, SymbolToken = "11351" },
                new Stock { Ticker = "PFIZER-EQ", Exchange = "NSE", Name = "PFIZER-EQ", Id = 363, SymbolToken = "2643" },
                new Stock { Ticker = "PHOENIXLTD-EQ", Exchange = "NSE", Name = "PHOENIXLTD-EQ", Id = 364, SymbolToken = "14552" },
                new Stock { Ticker = "PIDILITIND-EQ", Exchange = "NSE", Name = "PIDILITIND-EQ", Id = 365, SymbolToken = "2664" },
                new Stock { Ticker = "PEL-EQ", Exchange = "NSE", Name = "PEL-EQ", Id = 366, SymbolToken = "2412" },
                new Stock { Ticker = "PPLPHARMA-EQ", Exchange = "NSE", Name = "PPLPHARMA-EQ", Id = 367, SymbolToken = "11571" },
                new Stock { Ticker = "POLYMED-EQ", Exchange = "NSE", Name = "POLYMED-EQ", Id = 368, SymbolToken = "25718" },
                new Stock { Ticker = "POLYCAB-EQ", Exchange = "NSE", Name = "POLYCAB-EQ", Id = 369, SymbolToken = "9590" },
                new Stock { Ticker = "POONAWALLA-EQ", Exchange = "NSE", Name = "POONAWALLA-EQ", Id = 370, SymbolToken = "11403" },
                new Stock { Ticker = "PFC-EQ", Exchange = "NSE", Name = "PFC-EQ", Id = 371, SymbolToken = "14299" },
                new Stock { Ticker = "POWERGRID-EQ", Exchange = "NSE", Name = "POWERGRID-EQ", Id = 372, SymbolToken = "14977" },
                new Stock { Ticker = "PRAJIND-EQ", Exchange = "NSE", Name = "PRAJIND-EQ", Id = 373, SymbolToken = "2705" },
                new Stock { Ticker = "PRESTIGE-EQ", Exchange = "NSE", Name = "PRESTIGE-EQ", Id = 374, SymbolToken = "20302" },
                new Stock { Ticker = "PGHH-EQ", Exchange = "NSE", Name = "PGHH-EQ", Id = 375, SymbolToken = "2535" },
                new Stock { Ticker = "PNB-EQ", Exchange = "NSE", Name = "PNB-EQ", Id = 376, SymbolToken = "10666" },
                new Stock { Ticker = "QUESS-EQ", Exchange = "NSE", Name = "QUESS-EQ", Id = 377, SymbolToken = "17704" },
                new Stock { Ticker = "RRKABEL-EQ", Exchange = "NSE", Name = "RRKABEL-EQ", Id = 378, SymbolToken = "18566" },
                new Stock { Ticker = "RBLBANK-EQ", Exchange = "NSE", Name = "RBLBANK-EQ", Id = 379, SymbolToken = "18391" },
                new Stock { Ticker = "RECLTD-EQ", Exchange = "NSE", Name = "RECLTD-EQ", Id = 380, SymbolToken = "15355" },
                new Stock { Ticker = "RHIM-EQ", Exchange = "NSE", Name = "RHIM-EQ", Id = 381, SymbolToken = "31163" },
                new Stock { Ticker = "RITES-EQ", Exchange = "NSE", Name = "RITES-EQ", Id = 382, SymbolToken = "3761" },
                new Stock { Ticker = "RADICO-EQ", Exchange = "NSE", Name = "RADICO-EQ", Id = 383, SymbolToken = "10990" },
                new Stock { Ticker = "RVNL-EQ", Exchange = "NSE", Name = "RVNL-EQ", Id = 384, SymbolToken = "9552" },
                new Stock { Ticker = "RAILTEL-EQ", Exchange = "NSE", Name = "RAILTEL-EQ", Id = 385, SymbolToken = "2431" },
                new Stock { Ticker = "RAINBOW-EQ", Exchange = "NSE", Name = "RAINBOW-EQ", Id = 386, SymbolToken = "9408" },
                new Stock { Ticker = "RAJESHEXPO-EQ", Exchange = "NSE", Name = "RAJESHEXPO-EQ", Id = 387, SymbolToken = "7401" },
                new Stock { Ticker = "RKFORGE-EQ", Exchange = "NSE", Name = "RKFORGE-EQ", Id = 388, SymbolToken = "11411" },
                new Stock { Ticker = "RCF-EQ", Exchange = "NSE", Name = "RCF-EQ", Id = 389, SymbolToken = "2866" },
                new Stock { Ticker = "RATNAMANI-EQ", Exchange = "NSE", Name = "RATNAMANI-EQ", Id = 390, SymbolToken = "13451" },
                new Stock { Ticker = "RTNINDIA-EQ", Exchange = "NSE", Name = "RTNINDIA-EQ", Id = 391, SymbolToken = "27297" },
                new Stock { Ticker = "RAYMOND-EQ", Exchange = "NSE", Name = "RAYMOND-EQ", Id = 392, SymbolToken = "2859" },
                new Stock { Ticker = "REDINGTON-EQ", Exchange = "NSE", Name = "REDINGTON-EQ", Id = 393, SymbolToken = "14255" },
                new Stock { Ticker = "RELIANCE-EQ", Exchange = "NSE", Name = "RELIANCE-EQ", Id = 394, SymbolToken = "2885" },
                new Stock { Ticker = "ROUTE-EQ", Exchange = "NSE", Name = "ROUTE-EQ", Id = 395, SymbolToken = "128" },
                new Stock { Ticker = "SBFC-EQ", Exchange = "NSE", Name = "SBFC-EQ", Id = 396, SymbolToken = "18026" },
                new Stock { Ticker = "SBICARD-EQ", Exchange = "NSE", Name = "SBICARD-EQ", Id = 397, SymbolToken = "17971" },
                new Stock { Ticker = "SBILIFE-EQ", Exchange = "NSE", Name = "SBILIFE-EQ", Id = 398, SymbolToken = "21808" },
                new Stock { Ticker = "SJVN-EQ", Exchange = "NSE", Name = "SJVN-EQ", Id = 399, SymbolToken = "18883" },
                new Stock { Ticker = "SKFINDIA-EQ", Exchange = "NSE", Name = "SKFINDIA-EQ", Id = 400, SymbolToken = "3186" },
                new Stock { Ticker = "SRF-EQ", Exchange = "NSE", Name = "SRF-EQ", Id = 401, SymbolToken = "3273" },
                new Stock { Ticker = "SAMMAANCAP-EQ", Exchange = "NSE", Name = "SAMMAANCAP-EQ", Id = 402, SymbolToken = "30125" },
                new Stock { Ticker = "MOTHERSON-EQ", Exchange = "NSE", Name = "MOTHERSON-EQ", Id = 403, SymbolToken = "4204" },
                new Stock { Ticker = "SANOFI-EQ", Exchange = "NSE", Name = "SANOFI-EQ", Id = 404, SymbolToken = "1442" },
                new Stock { Ticker = "SAPPHIRE-EQ", Exchange = "NSE", Name = "SAPPHIRE-EQ", Id = 405, SymbolToken = "6718" },
                new Stock { Ticker = "SAREGAMA-EQ", Exchange = "NSE", Name = "SAREGAMA-EQ", Id = 406, SymbolToken = "4892" },
                new Stock { Ticker = "SCHAEFFLER-EQ", Exchange = "NSE", Name = "SCHAEFFLER-EQ", Id = 407, SymbolToken = "1011" },
                new Stock { Ticker = "SCHNEIDER-EQ", Exchange = "NSE", Name = "SCHNEIDER-EQ", Id = 408, SymbolToken = "31234" },
                new Stock { Ticker = "SCI-EQ", Exchange = "NSE", Name = "SCI-EQ", Id = 409, SymbolToken = "3048" },
                new Stock { Ticker = "SHREECEM-EQ", Exchange = "NSE", Name = "SHREECEM-EQ", Id = 410, SymbolToken = "3103" },
                new Stock { Ticker = "RENUKA-EQ", Exchange = "NSE", Name = "RENUKA-EQ", Id = 411, SymbolToken = "12026" },
                new Stock { Ticker = "SHRIRAMFIN-EQ", Exchange = "NSE", Name = "SHRIRAMFIN-EQ", Id = 412, SymbolToken = "4306" },
                new Stock { Ticker = "SHYAMMETL-EQ", Exchange = "NSE", Name = "SHYAMMETL-EQ", Id = 413, SymbolToken = "4693" },
                new Stock { Ticker = "SIEMENS-EQ", Exchange = "NSE", Name = "SIEMENS-EQ", Id = 414, SymbolToken = "3150" },
                new Stock { Ticker = "SIGNATURE-EQ", Exchange = "NSE", Name = "SIGNATURE-EQ", Id = 415, SymbolToken = "18743" },
                new Stock { Ticker = "SOBHA-EQ", Exchange = "NSE", Name = "SOBHA-EQ", Id = 416, SymbolToken = "13826" },
                new Stock { Ticker = "SOLARINDS-EQ", Exchange = "NSE", Name = "SOLARINDS-EQ", Id = 417, SymbolToken = "13332" },
                new Stock { Ticker = "SONACOMS-EQ", Exchange = "NSE", Name = "SONACOMS-EQ", Id = 418, SymbolToken = "4684" },
                new Stock { Ticker = "SONATSOFTW-EQ", Exchange = "NSE", Name = "SONATSOFTW-EQ", Id = 419, SymbolToken = "6596" },
                new Stock { Ticker = "STARHEALTH-EQ", Exchange = "NSE", Name = "STARHEALTH-EQ", Id = 420, SymbolToken = "7083" },
                new Stock { Ticker = "SBIN-EQ", Exchange = "NSE", Name = "SBIN-EQ", Id = 421, SymbolToken = "3045" },
                new Stock { Ticker = "SAIL-EQ", Exchange = "NSE", Name = "SAIL-EQ", Id = 422, SymbolToken = "2963" },
                new Stock { Ticker = "SWSOLAR-EQ", Exchange = "NSE", Name = "SWSOLAR-EQ", Id = 423, SymbolToken = "12489" },
                new Stock { Ticker = "SUMICHEM-EQ", Exchange = "NSE", Name = "SUMICHEM-EQ", Id = 424, SymbolToken = "17105" },
                new Stock { Ticker = "SPARC-EQ", Exchange = "NSE", Name = "SPARC-EQ", Id = 425, SymbolToken = "14788" },
                new Stock { Ticker = "SUNPHARMA-EQ", Exchange = "NSE", Name = "SUNPHARMA-EQ", Id = 426, SymbolToken = "3351" },
                new Stock { Ticker = "SUNTV-EQ", Exchange = "NSE", Name = "SUNTV-EQ", Id = 427, SymbolToken = "13404" },
                new Stock { Ticker = "SUNDARMFIN-EQ", Exchange = "NSE", Name = "SUNDARMFIN-EQ", Id = 428, SymbolToken = "3339" },
                new Stock { Ticker = "SUNDRMFAST-EQ", Exchange = "NSE", Name = "SUNDRMFAST-EQ", Id = 429, SymbolToken = "3345" },
                new Stock { Ticker = "SUPREMEIND-EQ", Exchange = "NSE", Name = "SUPREMEIND-EQ", Id = 430, SymbolToken = "3363" },
                new Stock { Ticker = "SUVENPHAR-EQ", Exchange = "NSE", Name = "SUVENPHAR-EQ", Id = 431, SymbolToken = "17945" },
                new Stock { Ticker = "SUZLON-EQ", Exchange = "NSE", Name = "SUZLON-EQ", Id = 432, SymbolToken = "12018" },
                new Stock { Ticker = "SWANENERGY-EQ", Exchange = "NSE", Name = "SWANENERGY-EQ", Id = 433, SymbolToken = "27095" },
                new Stock { Ticker = "SYNGENE-EQ", Exchange = "NSE", Name = "SYNGENE-EQ", Id = 434, SymbolToken = "10243" },
                new Stock { Ticker = "SYRMA-EQ", Exchange = "NSE", Name = "SYRMA-EQ", Id = 435, SymbolToken = "10793" },
                new Stock { Ticker = "TBOTEK-EQ", Exchange = "NSE", Name = "TBOTEK-EQ", Id = 436, SymbolToken = "23740" },
                new Stock { Ticker = "TVSMOTOR-EQ", Exchange = "NSE", Name = "TVSMOTOR-EQ", Id = 437, SymbolToken = "8479" },
                new Stock { Ticker = "TVSSCS-EQ", Exchange = "NSE", Name = "TVSSCS-EQ", Id = 438, SymbolToken = "18151" },
                new Stock { Ticker = "TANLA-EQ", Exchange = "NSE", Name = "TANLA-EQ", Id = 439, SymbolToken = "13976" },
                new Stock { Ticker = "TATACHEM-EQ", Exchange = "NSE", Name = "TATACHEM-EQ", Id = 440, SymbolToken = "3405" },
                new Stock { Ticker = "TATACOMM-EQ", Exchange = "NSE", Name = "TATACOMM-EQ", Id = 441, SymbolToken = "3721" },
                new Stock { Ticker = "TCS-EQ", Exchange = "NSE", Name = "TCS-EQ", Id = 442, SymbolToken = "11536" },
                new Stock { Ticker = "TATACONSUM-EQ", Exchange = "NSE", Name = "TATACONSUM-EQ", Id = 443, SymbolToken = "3432" },
                new Stock { Ticker = "TATAELXSI-EQ", Exchange = "NSE", Name = "TATAELXSI-EQ", Id = 444, SymbolToken = "3411" },
                new Stock { Ticker = "TATAINVEST-EQ", Exchange = "NSE", Name = "TATAINVEST-EQ", Id = 445, SymbolToken = "1621" },
                new Stock { Ticker = "TATAMOTORS-EQ", Exchange = "NSE", Name = "TATAMOTORS-EQ", Id = 446, SymbolToken = "3456" },
                new Stock { Ticker = "TATAPOWER-EQ", Exchange = "NSE", Name = "TATAPOWER-EQ", Id = 447, SymbolToken = "3426" },
                new Stock { Ticker = "TATASTEEL-EQ", Exchange = "NSE", Name = "TATASTEEL-EQ", Id = 448, SymbolToken = "3499" },
                new Stock { Ticker = "TATATECH-EQ", Exchange = "NSE", Name = "TATATECH-EQ", Id = 449, SymbolToken = "20293" },
                new Stock { Ticker = "TTML-EQ", Exchange = "NSE", Name = "TTML-EQ", Id = 450, SymbolToken = "8954" },
                new Stock { Ticker = "TECHM-EQ", Exchange = "NSE", Name = "TECHM-EQ", Id = 451, SymbolToken = "13538" },
                new Stock { Ticker = "TECHNOE-EQ", Exchange = "NSE", Name = "TECHNOE-EQ", Id = 452, SymbolToken = "6445" },
                new Stock { Ticker = "TEJASNET-EQ", Exchange = "NSE", Name = "TEJASNET-EQ", Id = 453, SymbolToken = "21131" },
                new Stock { Ticker = "NIACL-EQ", Exchange = "NSE", Name = "NIACL-EQ", Id = 454, SymbolToken = "399" },
                new Stock { Ticker = "RAMCOCEM-EQ", Exchange = "NSE", Name = "RAMCOCEM-EQ", Id = 455, SymbolToken = "2043" },
                new Stock { Ticker = "THERMAX-EQ", Exchange = "NSE", Name = "THERMAX-EQ", Id = 456, SymbolToken = "3475" },
                new Stock { Ticker = "TIMKEN-EQ", Exchange = "NSE", Name = "TIMKEN-EQ", Id = 457, SymbolToken = "14198" },
                new Stock { Ticker = "TITAGARH-EQ", Exchange = "NSE", Name = "TITAGARH-EQ", Id = 458, SymbolToken = "15414" },
                new Stock { Ticker = "TITAN-EQ", Exchange = "NSE", Name = "TITAN-EQ", Id = 459, SymbolToken = "3506" },
                new Stock { Ticker = "TORNTPHARM-EQ", Exchange = "NSE", Name = "TORNTPHARM-EQ", Id = 460, SymbolToken = "3518" },
                new Stock { Ticker = "TORNTPOWER-EQ", Exchange = "NSE", Name = "TORNTPOWER-EQ", Id = 461, SymbolToken = "13786" },
                new Stock { Ticker = "TRENT-EQ", Exchange = "NSE", Name = "TRENT-EQ", Id = 462, SymbolToken = "1964" },
                new Stock { Ticker = "TRIDENT-EQ", Exchange = "NSE", Name = "TRIDENT-EQ", Id = 463, SymbolToken = "9685" },
                new Stock { Ticker = "TRIVENI-EQ", Exchange = "NSE", Name = "TRIVENI-EQ", Id = 464, SymbolToken = "13081" },
                new Stock { Ticker = "TRITURBINE-EQ", Exchange = "NSE", Name = "TRITURBINE-EQ", Id = 465, SymbolToken = "25584" },
                new Stock { Ticker = "TIINDIA-EQ", Exchange = "NSE", Name = "TIINDIA-EQ", Id = 466, SymbolToken = "312" },
                new Stock { Ticker = "UCOBANK-EQ", Exchange = "NSE", Name = "UCOBANK-EQ", Id = 467, SymbolToken = "11223" },
                new Stock { Ticker = "UNOMINDA-EQ", Exchange = "NSE", Name = "UNOMINDA-EQ", Id = 468, SymbolToken = "14154" },
                new Stock { Ticker = "UPL-EQ", Exchange = "NSE", Name = "UPL-EQ", Id = 469, SymbolToken = "11287" },
                new Stock { Ticker = "UTIAMC-EQ", Exchange = "NSE", Name = "UTIAMC-EQ", Id = 470, SymbolToken = "527" },
                new Stock { Ticker = "UJJIVANSFB-EQ", Exchange = "NSE", Name = "UJJIVANSFB-EQ", Id = 471, SymbolToken = "15228" },
                new Stock { Ticker = "ULTRACEMCO-EQ", Exchange = "NSE", Name = "ULTRACEMCO-EQ", Id = 472, SymbolToken = "11532" },
                new Stock { Ticker = "UNIONBANK-EQ", Exchange = "NSE", Name = "UNIONBANK-EQ", Id = 473, SymbolToken = "10753" },
                new Stock { Ticker = "UBL-EQ", Exchange = "NSE", Name = "UBL-EQ", Id = 474, SymbolToken = "16713" },
                new Stock { Ticker = "UNITDSPR-EQ", Exchange = "NSE", Name = "UNITDSPR-EQ", Id = 475, SymbolToken = "10447" },
                new Stock { Ticker = "USHAMART-EQ", Exchange = "NSE", Name = "USHAMART-EQ", Id = 476, SymbolToken = "8840" },
                new Stock { Ticker = "VGUARD-EQ", Exchange = "NSE", Name = "VGUARD-EQ", Id = 477, SymbolToken = "15362" },
                new Stock { Ticker = "VIPIND-EQ", Exchange = "NSE", Name = "VIPIND-EQ", Id = 478, SymbolToken = "3703" },
                new Stock { Ticker = "DBREALTY-EQ", Exchange = "NSE", Name = "DBREALTY-EQ", Id = 479, SymbolToken = "18124" },
                new Stock { Ticker = "VTL-EQ", Exchange = "NSE", Name = "VTL-EQ", Id = 480, SymbolToken = "2073" },
                new Stock { Ticker = "VARROC-EQ", Exchange = "NSE", Name = "VARROC-EQ", Id = 481, SymbolToken = "3857" },
                new Stock { Ticker = "VBL-EQ", Exchange = "NSE", Name = "VBL-EQ", Id = 482, SymbolToken = "18921" },
                new Stock { Ticker = "MANYAVAR-EQ", Exchange = "NSE", Name = "MANYAVAR-EQ", Id = 483, SymbolToken = "8167" },
                new Stock { Ticker = "VEDL-EQ", Exchange = "NSE", Name = "VEDL-EQ", Id = 484, SymbolToken = "3063" },
                new Stock { Ticker = "VIJAYA-EQ", Exchange = "NSE", Name = "VIJAYA-EQ", Id = 485, SymbolToken = "5585" },
                new Stock { Ticker = "VINATIORGA-EQ", Exchange = "NSE", Name = "VINATIORGA-EQ", Id = 486, SymbolToken = "17364" },
                new Stock { Ticker = "IDEA-EQ", Exchange = "NSE", Name = "IDEA-EQ", Id = 487, SymbolToken = "14366" },
                new Stock { Ticker = "VOLTAS-EQ", Exchange = "NSE", Name = "VOLTAS-EQ", Id = 488, SymbolToken = "3718" },
                new Stock { Ticker = "WELCORP-EQ", Exchange = "NSE", Name = "WELCORP-EQ", Id = 489, SymbolToken = "11821" },
                new Stock { Ticker = "WELSPUNLIV-EQ", Exchange = "NSE", Name = "WELSPUNLIV-EQ", Id = 490, SymbolToken = "11253" },
                new Stock { Ticker = "WESTLIFE-EQ", Exchange = "NSE", Name = "WESTLIFE-EQ", Id = 491, SymbolToken = "11580" },
                new Stock { Ticker = "WHIRLPOOL-EQ", Exchange = "NSE", Name = "WHIRLPOOL-EQ", Id = 492, SymbolToken = "18011" },
                new Stock { Ticker = "WIPRO-EQ", Exchange = "NSE", Name = "WIPRO-EQ", Id = 493, SymbolToken = "3787" },
                new Stock { Ticker = "YESBANK-EQ", Exchange = "NSE", Name = "YESBANK-EQ", Id = 494, SymbolToken = "11915" },
                new Stock { Ticker = "ZFCVINDIA-EQ", Exchange = "NSE", Name = "ZFCVINDIA-EQ", Id = 495, SymbolToken = "16915" },
                new Stock { Ticker = "ZEEL-EQ", Exchange = "NSE", Name = "ZEEL-EQ", Id = 496, SymbolToken = "3812" },
                new Stock { Ticker = "ZENSARTECH-EQ", Exchange = "NSE", Name = "ZENSARTECH-EQ", Id = 497, SymbolToken = "1076" },
                new Stock { Ticker = "ZOMATO-EQ", Exchange = "NSE", Name = "ZOMATO-EQ", Id = 498, SymbolToken = "5097" },
                new Stock { Ticker = "ZYDUSLIFE-EQ", Exchange = "NSE", Name = "ZYDUSLIFE-EQ", Id = 499, SymbolToken = "7929" },
                new Stock { Ticker = "ECLERX-EQ", Exchange = "NSE", Name = "ECLERX-EQ", Id = 500, SymbolToken = "15179" },


            };
    }

    //public static List<Stock> GetStocks()
    //{
    //  return new List<Stock>
    //    {

    //        ////NIFTY 50
    //        new Stock { Ticker = "ADANIENT-EQ", Exchange = "NSE", Name = "ADANIENT-EQ", Id = 14, SymbolToken = "25" },
    //        new Stock { Ticker = "ADANIPORTS-EQ", Exchange = "NSE", Name = "ADANIPORTS-EQ", Id = 16, SymbolToken = "15083" },
    //        new Stock { Ticker = "APOLLOHOSP-EQ", Exchange = "NSE", Name = "APOLLOHOSP-EQ", Id = 39, SymbolToken = "157" },
    //        new Stock { Ticker = "ASIANPAINT-EQ", Exchange = "NSE", Name = "ASIANPAINT-EQ", Id = 45, SymbolToken = "236" },
    //        new Stock { Ticker = "AXISBANK-EQ", Exchange = "NSE", Name = "AXISBANK-EQ", Id = 53, SymbolToken = "5900" },
    //        new Stock { Ticker = "BAJAJ-AUTO-EQ", Exchange = "NSE", Name = "BAJAJ-AUTO-EQ", Id = 58, SymbolToken = "16669" },
    //        new Stock { Ticker = "BAJFINANCE-EQ", Exchange = "NSE", Name = "BAJFINANCE-EQ", Id = 59, SymbolToken = "317" },
    //        new Stock { Ticker = "BAJAJFINSV-EQ", Exchange = "NSE", Name = "BAJAJFINSV-EQ", Id = 60, SymbolToken = "16675" },
    //        new Stock { Ticker = "BEL-EQ", Exchange = "NSE", Name = "BEL-EQ", Id = 73, SymbolToken = "383" },
    //        new Stock { Ticker = "BPCL-EQ", Exchange = "NSE", Name = "BPCL-EQ", Id = 76, SymbolToken = "526" },
    //        new Stock { Ticker = "BHARTIARTL-EQ", Exchange = "NSE", Name = "BHARTIARTL-EQ", Id = 77, SymbolToken = "10604" },
    //        new Stock { Ticker = "BRITANNIA-EQ", Exchange = "NSE", Name = "BRITANNIA-EQ", Id = 88, SymbolToken = "547" },
    //        new Stock { Ticker = "CIPLA-EQ", Exchange = "NSE", Name = "CIPLA-EQ", Id = 114, SymbolToken = "694" },
    //        new Stock { Ticker = "COALINDIA-EQ", Exchange = "NSE", Name = "COALINDIA-EQ", Id = 117, SymbolToken = "20374" },
    //        new Stock { Ticker = "DRREDDY-EQ", Exchange = "NSE", Name = "DRREDDY-EQ", Id = 142, SymbolToken = "881" },
    //        new Stock { Ticker = "EICHERMOT-EQ", Exchange = "NSE", Name = "EICHERMOT-EQ", Id = 146, SymbolToken = "910" },
    //        new Stock { Ticker = "GRASIM-EQ", Exchange = "NSE", Name = "GRASIM-EQ", Id = 186, SymbolToken = "1232" },
    //        new Stock { Ticker = "HCLTECH-EQ", Exchange = "NSE", Name = "HCLTECH-EQ", Id = 199, SymbolToken = "7229" },
    //        new Stock { Ticker = "HDFCBANK-EQ", Exchange = "NSE", Name = "HDFCBANK-EQ", Id = 201, SymbolToken = "1333" },
    //        new Stock { Ticker = "HDFCLIFE-EQ", Exchange = "NSE", Name = "HDFCLIFE-EQ", Id = 202, SymbolToken = "467" },
    //        new Stock { Ticker = "HEROMOTOCO-EQ", Exchange = "NSE", Name = "HEROMOTOCO-EQ", Id = 206, SymbolToken = "1348" },
    //        new Stock { Ticker = "HINDALCO-EQ", Exchange = "NSE", Name = "HINDALCO-EQ", Id = 208, SymbolToken = "1363" },
    //        new Stock { Ticker = "HINDUNILVR-EQ", Exchange = "NSE", Name = "HINDUNILVR-EQ", Id = 212, SymbolToken = "1394" },
    //        new Stock { Ticker = "ICICIBANK-EQ", Exchange = "NSE", Name = "ICICIBANK-EQ", Id = 219, SymbolToken = "4963" },
    //        new Stock { Ticker = "ITC-EQ", Exchange = "NSE", Name = "ITC-EQ", Id = 230, SymbolToken = "1660" },
    //        new Stock { Ticker = "INDUSINDBK-EQ", Exchange = "NSE", Name = "INDUSINDBK-EQ", Id = 245, SymbolToken = "5258" },
    //        new Stock { Ticker = "INFY-EQ", Exchange = "NSE", Name = "INFY-EQ", Id = 247, SymbolToken = "1594" },
    //        new Stock { Ticker = "JSWSTEEL-EQ", Exchange = "NSE", Name = "JSWSTEEL-EQ", Id = 260, SymbolToken = "11723" },
    //        new Stock { Ticker = "KOTAKBANK-EQ", Exchange = "NSE", Name = "KOTAKBANK-EQ", Id = 289, SymbolToken = "1922" },
    //        new Stock { Ticker = "LT-EQ", Exchange = "NSE", Name = "LT-EQ", Id = 295, SymbolToken = "11483" },
    //        new Stock { Ticker = "M%26M-EQ", Exchange = "NSE", Name = "M%26M-EQ", Id = 309, SymbolToken = "2031" },
    //        new Stock { Ticker = "MARUTI-EQ", Exchange = "NSE", Name = "MARUTI-EQ", Id = 315, SymbolToken = "10999" },
    //        new Stock { Ticker = "NTPC-EQ", Exchange = "NSE", Name = "NTPC-EQ", Id = 335, SymbolToken = "11630" },
    //        new Stock { Ticker = "NESTLEIND-EQ", Exchange = "NSE", Name = "NESTLEIND-EQ", Id = 339, SymbolToken = "17963" },
    //        new Stock { Ticker = "ONGC-EQ", Exchange = "NSE", Name = "ONGC-EQ", Id = 347, SymbolToken = "2475" },
    //        new Stock { Ticker = "POWERGRID-EQ", Exchange = "NSE", Name = "POWERGRID-EQ", Id = 372, SymbolToken = "14977" },
    //        new Stock { Ticker = "RELIANCE-EQ", Exchange = "NSE", Name = "RELIANCE-EQ", Id = 394, SymbolToken = "2885" },
    //        new Stock { Ticker = "SBILIFE-EQ", Exchange = "NSE", Name = "SBILIFE-EQ", Id = 398, SymbolToken = "21808" },
    //        new Stock { Ticker = "SHRIRAMFIN-EQ", Exchange = "NSE", Name = "SHRIRAMFIN-EQ", Id = 412, SymbolToken = "4306" },
    //        new Stock { Ticker = "SBIN-EQ", Exchange = "NSE", Name = "SBIN-EQ", Id = 421, SymbolToken = "3045" },
    //        new Stock { Ticker = "SUNPHARMA-EQ", Exchange = "NSE", Name = "SUNPHARMA-EQ", Id = 426, SymbolToken = "3351" },
    //        new Stock { Ticker = "TCS-EQ", Exchange = "NSE", Name = "TCS-EQ", Id = 442, SymbolToken = "11536" },
    //        new Stock { Ticker = "TATACONSUM-EQ", Exchange = "NSE", Name = "TATACONSUM-EQ", Id = 443, SymbolToken = "3432" },
    //        new Stock { Ticker = "TATAMOTORS-EQ", Exchange = "NSE", Name = "TATAMOTORS-EQ", Id = 446, SymbolToken = "3456" },
    //        new Stock { Ticker = "TATASTEEL-EQ", Exchange = "NSE", Name = "TATASTEEL-EQ", Id = 448, SymbolToken = "3499" },
    //        new Stock { Ticker = "TECHM-EQ", Exchange = "NSE", Name = "TECHM-EQ", Id = 451, SymbolToken = "13538" },
    //        new Stock { Ticker = "TITAN-EQ", Exchange = "NSE", Name = "TITAN-EQ", Id = 459, SymbolToken = "3506" },
    //        new Stock { Ticker = "TRENT-EQ", Exchange = "NSE", Name = "TRENT-EQ", Id = 462, SymbolToken = "1964" },
    //        new Stock { Ticker = "ULTRACEMCO-EQ", Exchange = "NSE", Name = "ULTRACEMCO-EQ", Id = 472, SymbolToken = "11532" },
    //        new Stock { Ticker = "WIPRO-EQ", Exchange = "NSE", Name = "WIPRO-EQ", Id = 493, SymbolToken = "3787" },




    //    };
    //}



  }
}
